version: '3'

volumes:
    db: # mount it internally instead of a folder. it avoids file lock problems

services:
    app:
        env_file:
            - .env
        container_name: awesome_nest_boilerplate
        restart: always
        build: .
        ports:
            - '$PORT:$PORT'
        links:
            - mysql

    mysql:
        image: mysql
        container_name: mysql
        restart: always
        environment:
            MYSQL_PASSWORD: mysql
            TZ: 'GMT'
            PGTZ: 'GMT'
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/mysql/data

    adminer:
        image: adminer
        restart: always
        links:
            - mysql
        ports:
            - '8081:8080' # to avoid conflicting the 8080 default for many cloud providers
